[
    "[
        \"GITHUB_USERNAME={{env.GITHUB_USERNAME}}\"
    ]
    [
        \"GITHUB_TOKEN={{env.GITHUB_TOKEN}}\"
    ]
    [
        \"SPRING_PROFILE={{env.SPRING_PROFILE}}\"
    ]
    [
        \"SPRING_PORT={{env.SPRING_PORT}}\"
    ]
    [
        \"FOTG_MONGO_URI={{env.FOTG_MONGO_URI}}\"
    ]"
]

docker build --build-arg SPRING_PROFILE={{env.SPRING_PROFILE}} --build-arg SPRING_PORT={{env.SPRING_PORT}} --build-arg GITHUB_USERNAME={{env.GITHUB_USERNAME}} --build-arg GITHUB_TOKEN={{env.GITHUB_TOKEN}} --build-arg FOTG_MONGO_URI={{env.FOTG_MONGO_URI}} -t fallofthegods-data .