name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
     uses: GY-CODING/.github/.github/workflows/koyeb-deploy.yml@master
     secrets: inherit
     with: 
       project-name: "fallofthegods-data"
       project-id: "e579933a-ea26-4c5d-920c-7e9e65738216"
