name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
     # uses: GY-CODING/.github/.github/workflows/koyeb-deploy.yml@master
     # secrets: inherit
     # with: 
     #   project-name: "fallofthegods-data"
     #   project-id: "fall-of-the-gods"
